In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential, load_model
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.optimizers import Adam
from keras.utils import np_utils
from sklearn import metrics 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

Using TensorFlow backend.
/home/felipe/miniconda3/envs/lingua_env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/felipe/miniconda3/envs/lingua_env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/felipe/miniconda3/envs/lingua_env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home

In [2]:
df = pd.read_pickle('sound_db.pkl')
df_train = df
#df_train = pd.concat([df[df['lang']=='es_es'].iloc[:150,],df[df['lang']=='sv'].iloc[:150,],df[df['lang']=='fr'].iloc[:150,],df[df['lang']=='pt_br'].iloc[:150,]])
df_t, df_val = train_test_split(df_train, test_size=0.2, random_state=42)

In [31]:
X = np.array(df_t['feature_vector'].tolist())
y = np.array(df_t['lang'].tolist())
val_x = np.array(df_val['feature_vector'].tolist())
val_y = np.array(df_val['lang'].tolist())

lb = LabelEncoder()

y = np_utils.to_categorical(lb.fit_transform(y))
val_y = np_utils.to_categorical(lb.transform(val_y))

In [17]:
num_labels = y.shape[1]
filter_size = 2

# build model
model = Sequential()

model.add(Dense(512, input_shape=(540,)))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(num_labels))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

In [18]:
model.fit(X, y, batch_size=32, epochs=500, validation_data=(val_x, val_y))

Train on 1801 samples, validate on 451 samples
Epoch 1/500
1801/1801 [==============================] - 1s 664us/step - loss: 9.3505 - acc: 0.3331 - val_loss: 7.7319 - val_acc: 0.4035
Epoch 2/500
1801/1801 [==============================] - 1s 378us/step - loss: 7.5200 - acc: 0.4586 - val_loss: 7.8395 - val_acc: 0.4590
Epoch 3/500
1801/1801 [==============================] - 1s 380us/step - loss: 6.6086 - acc: 0.5230 - val_loss: 6.2221 - val_acc: 0.5410
Epoch 4/500
1801/1801 [==============================] - 1s 385us/step - loss: 5.7758 - acc: 0.5425 - val_loss: 3.7501 - val_acc: 0.6098
Epoch 5/500
1801/1801 [==============================] - 1s 417us/step - loss: 4.1623 - acc: 0.6063 - val_loss: 1.9371 - val_acc: 0.7317
Epoch 6/500
1801/1801 [==============================] - 1s 405us/step - loss: 1.9944 - acc: 0.6835 - val_loss: 0.8759 - val_acc: 0.7627
Epoch 7/500
1801/1801 [==============================] - 1s 389us/step - loss: 0.8768 - acc: 0.7579 - val_loss: 0.4804 - val_acc: 0

1801/1801 [==============================] - 1s 380us/step - loss: 0.0683 - acc: 0.9795 - val_loss: 0.1137 - val_acc: 0.9690
Epoch 61/500
1801/1801 [==============================] - 1s 374us/step - loss: 0.0746 - acc: 0.9778 - val_loss: 0.1638 - val_acc: 0.9601
Epoch 62/500
1801/1801 [==============================] - 1s 374us/step - loss: 0.0905 - acc: 0.9728 - val_loss: 0.2022 - val_acc: 0.9645
Epoch 63/500
1801/1801 [==============================] - 1s 375us/step - loss: 0.0515 - acc: 0.9833 - val_loss: 0.1863 - val_acc: 0.9645
Epoch 64/500
1801/1801 [==============================] - 1s 378us/step - loss: 0.0653 - acc: 0.9783 - val_loss: 0.1825 - val_acc: 0.9623
Epoch 65/500
1801/1801 [==============================] - 1s 378us/step - loss: 0.0551 - acc: 0.9856 - val_loss: 0.1657 - val_acc: 0.9667
Epoch 66/500
1801/1801 [==============================] - 1s 374us/step - loss: 0.0553 - acc: 0.9811 - val_loss: 0.1895 - val_acc: 0.9601
Epoch 67/500
1801/1801 [=======================

1801/1801 [==============================] - 1s 387us/step - loss: 0.0855 - acc: 0.9728 - val_loss: 0.2001 - val_acc: 0.9645
Epoch 120/500
1801/1801 [==============================] - 1s 391us/step - loss: 0.0886 - acc: 0.9739 - val_loss: 0.2699 - val_acc: 0.9512
Epoch 121/500
1801/1801 [==============================] - 1s 336us/step - loss: 0.0313 - acc: 0.9900 - val_loss: 0.1567 - val_acc: 0.9690
Epoch 122/500
1801/1801 [==============================] - 1s 375us/step - loss: 0.0442 - acc: 0.9850 - val_loss: 0.1787 - val_acc: 0.9667
Epoch 123/500
1801/1801 [==============================] - 1s 364us/step - loss: 0.0338 - acc: 0.9883 - val_loss: 0.1632 - val_acc: 0.9712
Epoch 124/500
1801/1801 [==============================] - 1s 354us/step - loss: 0.0507 - acc: 0.9883 - val_loss: 0.1427 - val_acc: 0.9645
Epoch 125/500
1801/1801 [==============================] - 1s 365us/step - loss: 0.0623 - acc: 0.9833 - val_loss: 0.2016 - val_acc: 0.9712
Epoch 126/500
1801/1801 [================

1801/1801 [==============================] - 1s 405us/step - loss: 0.0510 - acc: 0.9878 - val_loss: 0.1992 - val_acc: 0.9734
Epoch 179/500
1801/1801 [==============================] - 1s 484us/step - loss: 0.0503 - acc: 0.9889 - val_loss: 0.2176 - val_acc: 0.9712
Epoch 180/500
1801/1801 [==============================] - 1s 359us/step - loss: 0.0351 - acc: 0.9922 - val_loss: 0.2227 - val_acc: 0.9734
Epoch 181/500
1801/1801 [==============================] - 1s 335us/step - loss: 0.0316 - acc: 0.9906 - val_loss: 0.2183 - val_acc: 0.9667
Epoch 182/500
1801/1801 [==============================] - 1s 335us/step - loss: 0.0276 - acc: 0.9911 - val_loss: 0.2711 - val_acc: 0.9557
Epoch 183/500
1801/1801 [==============================] - 1s 334us/step - loss: 0.0383 - acc: 0.9900 - val_loss: 0.1931 - val_acc: 0.9823
Epoch 184/500
1801/1801 [==============================] - 1s 367us/step - loss: 0.0461 - acc: 0.9917 - val_loss: 0.2232 - val_acc: 0.9734
Epoch 185/500
1801/1801 [================

1801/1801 [==============================] - 1s 338us/step - loss: 0.0449 - acc: 0.9895 - val_loss: 0.2450 - val_acc: 0.9756
Epoch 238/500
1801/1801 [==============================] - 1s 337us/step - loss: 0.0299 - acc: 0.9906 - val_loss: 0.2323 - val_acc: 0.9734
Epoch 239/500
1801/1801 [==============================] - 1s 335us/step - loss: 0.0289 - acc: 0.9906 - val_loss: 0.2673 - val_acc: 0.9667
Epoch 240/500
1801/1801 [==============================] - 1s 339us/step - loss: 0.0426 - acc: 0.9872 - val_loss: 0.3365 - val_acc: 0.9579
Epoch 241/500
1801/1801 [==============================] - 1s 352us/step - loss: 0.0485 - acc: 0.9861 - val_loss: 0.2122 - val_acc: 0.9667
Epoch 242/500
1801/1801 [==============================] - 1s 343us/step - loss: 0.0406 - acc: 0.9895 - val_loss: 0.2573 - val_acc: 0.9645
Epoch 243/500
1801/1801 [==============================] - 1s 347us/step - loss: 0.0203 - acc: 0.9939 - val_loss: 0.2118 - val_acc: 0.9690
Epoch 244/500
1801/1801 [================

1801/1801 [==============================] - 1s 381us/step - loss: 0.0445 - acc: 0.9895 - val_loss: 0.2205 - val_acc: 0.9756
Epoch 297/500
1801/1801 [==============================] - 1s 396us/step - loss: 0.0397 - acc: 0.9928 - val_loss: 0.2207 - val_acc: 0.9667
Epoch 298/500
1801/1801 [==============================] - 1s 380us/step - loss: 0.0124 - acc: 0.9956 - val_loss: 0.2236 - val_acc: 0.9712
Epoch 299/500
1801/1801 [==============================] - 1s 381us/step - loss: 0.0522 - acc: 0.9906 - val_loss: 0.2384 - val_acc: 0.9734
Epoch 300/500
1801/1801 [==============================] - 1s 378us/step - loss: 0.0479 - acc: 0.9861 - val_loss: 0.2320 - val_acc: 0.9712
Epoch 301/500
1801/1801 [==============================] - 1s 424us/step - loss: 0.0244 - acc: 0.9922 - val_loss: 0.2133 - val_acc: 0.9712
Epoch 302/500
1801/1801 [==============================] - 1s 335us/step - loss: 0.0269 - acc: 0.9911 - val_loss: 0.1627 - val_acc: 0.9845
Epoch 303/500
1801/1801 [================

1801/1801 [==============================] - 1s 377us/step - loss: 0.0282 - acc: 0.9922 - val_loss: 0.1986 - val_acc: 0.9712
Epoch 356/500
1801/1801 [==============================] - 1s 382us/step - loss: 0.0397 - acc: 0.9906 - val_loss: 0.1575 - val_acc: 0.9800
Epoch 357/500
1801/1801 [==============================] - 1s 377us/step - loss: 0.0197 - acc: 0.9933 - val_loss: 0.1765 - val_acc: 0.9800
Epoch 358/500
1801/1801 [==============================] - 1s 382us/step - loss: 0.0404 - acc: 0.9917 - val_loss: 0.1963 - val_acc: 0.9712
Epoch 359/500
1801/1801 [==============================] - 1s 378us/step - loss: 0.0349 - acc: 0.9911 - val_loss: 0.2234 - val_acc: 0.9734
Epoch 360/500
1801/1801 [==============================] - 1s 457us/step - loss: 0.0507 - acc: 0.9889 - val_loss: 0.1864 - val_acc: 0.9756
Epoch 361/500
1801/1801 [==============================] - 1s 385us/step - loss: 0.0682 - acc: 0.9900 - val_loss: 0.2096 - val_acc: 0.9690
Epoch 362/500
1801/1801 [================

1801/1801 [==============================] - 1s 477us/step - loss: 0.0221 - acc: 0.9956 - val_loss: 0.2359 - val_acc: 0.9712
Epoch 415/500
1801/1801 [==============================] - 1s 437us/step - loss: 0.0486 - acc: 0.9922 - val_loss: 0.3531 - val_acc: 0.9557
Epoch 416/500
1801/1801 [==============================] - 1s 431us/step - loss: 0.0337 - acc: 0.9933 - val_loss: 0.2448 - val_acc: 0.9756
Epoch 417/500
1801/1801 [==============================] - 1s 423us/step - loss: 0.0180 - acc: 0.9939 - val_loss: 0.2210 - val_acc: 0.9690
Epoch 418/500
1801/1801 [==============================] - 1s 413us/step - loss: 0.0151 - acc: 0.9933 - val_loss: 0.2312 - val_acc: 0.9712
Epoch 419/500
1801/1801 [==============================] - 1s 401us/step - loss: 0.0328 - acc: 0.9911 - val_loss: 0.2173 - val_acc: 0.9667
Epoch 420/500
1801/1801 [==============================] - 1s 428us/step - loss: 0.0316 - acc: 0.9922 - val_loss: 0.2978 - val_acc: 0.9645
Epoch 421/500
1801/1801 [================

1801/1801 [==============================] - 1s 391us/step - loss: 0.0574 - acc: 0.9895 - val_loss: 0.3577 - val_acc: 0.9601
Epoch 474/500
1801/1801 [==============================] - 1s 377us/step - loss: 0.0283 - acc: 0.9950 - val_loss: 0.3027 - val_acc: 0.9690
Epoch 475/500
1801/1801 [==============================] - 1s 374us/step - loss: 0.0248 - acc: 0.9961 - val_loss: 0.2936 - val_acc: 0.9712
Epoch 476/500
1801/1801 [==============================] - 1s 371us/step - loss: 0.0434 - acc: 0.9922 - val_loss: 0.3136 - val_acc: 0.9712
Epoch 477/500
1801/1801 [==============================] - 1s 374us/step - loss: 0.0253 - acc: 0.9961 - val_loss: 0.3028 - val_acc: 0.9667
Epoch 478/500
1801/1801 [==============================] - 1s 371us/step - loss: 0.0356 - acc: 0.9928 - val_loss: 0.2870 - val_acc: 0.9690
Epoch 479/500
1801/1801 [==============================] - 1s 375us/step - loss: 0.0517 - acc: 0.9911 - val_loss: 0.2890 - val_acc: 0.9712
Epoch 480/500
1801/1801 [================

In [38]:
pred_y = model.predict(val_x)

In [40]:
val_y

array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       ...,
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]], dtype=float32)

In [39]:
pred_y

array([[3.6850389e-07, 3.3807981e-09, 4.1915038e-05, 9.9995768e-01],
       [6.5464657e-15, 1.0000000e+00, 6.7765452e-15, 2.6002520e-15],
       [6.8345958e-37, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       ...,
       [1.0000000e+00, 6.5553148e-29, 2.8705244e-34, 9.0118830e-29],
       [1.0000000e+00, 1.2902527e-28, 0.0000000e+00, 7.2738104e-36],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00]],
      dtype=float32)

In [48]:
lb.inverse_transform([1])

array(['fr'], dtype='<U5')

In [20]:
def getMax(values):
    for i in range(4):
        if values[i] == max(values):
            values[i] = 1
        else:
            values[i] = 0
    return values

In [21]:
pred_y_bin = np.apply_along_axis(getMax,1,pred_y)

In [41]:
pred_y_bin

array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       ...,
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]], dtype=float32)

In [22]:
def getTrue(values):
    return all(values==True)

In [23]:
true = (pred_y_bin==val_y)

In [24]:
res = np.apply_along_axis(getTrue,1,true)

In [25]:
import pandas as pd
res = pd.Series(res)
res.value_counts()

True     439
False     12
dtype: int64

In [60]:
quijote = pd.read_pickle('rocio.pkl')
X_quijote = np.array(quijote['feature_vector'].tolist())
quijote_y = model.predict(X_quijote)

/home/felipe/miniconda3/envs/lingua_env/lib/python3.7/site-packages/numpy/core/_asarray.py:85: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)


In [61]:
quijote_y, lb.inverse_transform([0,1,2,3])

(array([[1., 0., 0., 0.]], dtype=float32),
 array(['es_es', 'fr', 'pt_br', 'sv'], dtype='<U5'))

In [65]:
69/11 -batch 32 - epoch 500

0.3875

In [ ]:
70/10 -batch 32 - epoch 500 - dense 512 512

In [ ]:
113/7 -batch 32 - epoch 500 - dense 512 512 - 150 from each lang

In [ ]:
66/14 -batch 5 - epoch 500

In [ ]:
65/15 -batch 32 - epoch 500 - one more layer